/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihan1;
import latihan1.ObjectWithPureFunction;

public class App {
    public static void main(String[] args) {

        ObjectWithPureFunction data = new ObjectWithPureFunction();
        // int test = data.sum(3, 5);
        System.out.print(data.sum(3, 6));
    }
}
