/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bangun;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.Arrays;
import java.util.Collection;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

import klas.Rectangle;
import klas.Point;

public class AppTest {
    // @Test public void testAppHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    // }
    @Test
    public void main() {
		
        // Declare and create a point object and two rectangle objects.
        Point originOne = new Point(23, 94);
        Rectangle rectOne = new Rectangle(originOne, 100, 200);
        // Rectangle rectTwo = new Rectangle(50, 100);
        assertEquals(20000, rectOne.getArea());

    }
}
