/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mariatest;

import java.sql.*;

public class App {

    public static void main( String[] args ) throws SQLException {
        //create connection for a server installed in localhost, with a user "root" with no password
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost/kreasi_batik", "root", null)) {
            // create a Statement
            try (Statement stmt = conn.createStatement()) {
                //execute query
                try (ResultSet rs = stmt.executeQuery("SELECT * from tb_jenis_kain")) {
                    //position result to first
                    // rs.first();
                    while (rs.next()) {
                        System.out.println(rs.getString("nama_kain")); //result is "Hello World!"
                    }
                }
            }
        }
    }
}
