/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blajartest2;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.Arrays;
import java.util.Collection;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

// public class AppTest {
//     @Test public void testAppHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//     }
// }

@RunWith(Parameterized.class)
public class AppTest {

    private int m1;
    private int m2;

    public AppTest(int p1, int p2) {
        m1 = p1;
        m2 = p2;
    }

    // creates the test data
    @Parameters
    public static Collection<Object[]> data() {
        Object[][] data = new Object[][] { { 1 , 2 }, { 5, 3 }, { 121, 4 } };
        return Arrays.asList(data);
    }


    @Test
    public void testMultiplyException() {
        App tester = new App();
        assertEquals("Result", m1 * m2, tester.kali(m1, m2));
    }
}
