/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blajartest2;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public int kali(int a, int b){

    	return a * b;
    }

    public static void main(String[] args) {

    	App test = new App();

    	System.out.println(test.kali(3, 5));

        // System.out.println(new App().getGreeting());
    }
}