/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testmongo;

import com.mongodb.client.FindIterable; 
import com.mongodb.client.MongoCollection; 
import com.mongodb.client.MongoDatabase;  

import java.util.Iterator; 
import org.bson.Document; 
import com.mongodb.MongoClient; 
import com.mongodb.MongoCredential; 

public class App {
    public static void main(String[] args) {
        // Creating a Mongo client 
      // Creating a Mongo client 
      MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
      
      // Accessing the database 
      MongoDatabase database = mongo.getDatabase("test");  
      
      // Retrieving a collection 
      MongoCollection<Document> collection = database.getCollection("collection");
    //   System.out.println("Collection sampleCollection selected successfully"); 

      // Getting the iterable object 
      FindIterable<Document> iterDoc = collection.find(); 
    //   int i = 1; 

    //   // Getting the iterator 
    //   Iterator it = iterDoc.iterator(); 
    
    //   while (it.hasNext()) {  
    //      System.out.println(it.next());   
    //   i++; 
    //   }
        Document document = new Document("name", "Munyi") 
        .append("age", "40")
        .append("status", "pending");  
        collection.insertOne(document); 

        for(Document doc:iterDoc)
        {
            System.out.println(doc.get("name"));
        }
    }

}
